# Special workspace

bind = SUPER, O, togglespecialworkspace, openrgb
bind = SUPER, U, togglespecialworkspace, pavucontrol
bind = SUPER, E, togglespecialworkspace, btop
bind = SUPER, M, togglespecialworkspace, spotify


