# Special workspace

bind = SUPER, O, togglespecialworkspace, openrgb

bind = SUPER, U, togglespecialworkspace, wiremix
bind = SUPER, E, togglespecialworkspace, btop

bind = SUPER, M, togglespecialworkspace, spotify


