# This part is from the Jakoolit dotfiles

bind = CTRL ALT, Delete, exec, hyprctl dispatch exit 0
bind = SUPER, Q, killactive,
bind = SUPER, F, fullscreen
bind = SUPER SHIFT, F, togglefloating,
bind = SUPER ALT, F, exec, hyprctl dispatch workspaceopt allfloat


# Resize windows
binde = SUPER SHIFT, h, resizeactive,-50 0
binde = SUPER SHIFT, l, resizeactive,50 0
binde = SUPER SHIFT, k, resizeactive,0 -50
binde = SUPER SHIFT, j, resizeactive,0 50

# Move windows
bind = SUPER CTRL, h, movewindow, l
bind = SUPER CTRL, l, movewindow, r
bind = SUPER CTRL, k, movewindow, u
bind = SUPER CTRL, j, movewindow, d

# Move focus with mainMod + arrow keys
# Did a weird exchange of keys for k and j
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

# Workspaces related
bind = SUPER, tab, workspace, m+1
bind = SUPER SHIFT, tab, workspace, m-1


bind = SUPER, code:10, workspace, 1
bind = SUPER, code:11, workspace, 2
bind = SUPER, code:12, workspace, 3
bind = SUPER, code:13, workspace, 4
bind = SUPER, code:14, workspace, 5
bind = SUPER, code:15, workspace, 6
bind = SUPER, code:16, workspace, 7
bind = SUPER, code:17, workspace, 8
bind = SUPER, code:18, workspace, 9
bind = SUPER, code:19, workspace, 10

# Move active window and follow to workspace mainMod + SHIFT [0-9]
bind = SUPER SHIFT, code:10, movetoworkspace, 1
bind = SUPER SHIFT, code:11, movetoworkspace, 2
bind = SUPER SHIFT, code:12, movetoworkspace, 3
bind = SUPER SHIFT, code:13, movetoworkspace, 4
bind = SUPER SHIFT, code:14, movetoworkspace, 5
bind = SUPER SHIFT, code:15, movetoworkspace, 6
bind = SUPER SHIFT, code:16, movetoworkspace, 7
bind = SUPER SHIFT, code:17, movetoworkspace, 8
bind = SUPER SHIFT, code:18, movetoworkspace, 9
bind = SUPER SHIFT, code:19, movetoworkspace, 10
bind = SUPER SHIFT, bracketleft, movetoworkspace, -1 # brackets [ or ]
bind = SUPER SHIFT, bracketright, movetoworkspace, +1

# Move active window to a workspace silently mainMod + CTRL [0-9]
bind = SUPER CTRL, code:10, movetoworkspacesilent, 1
bind = SUPER CTRL, code:11, movetoworkspacesilent, 2
bind = SUPER CTRL, code:12, movetoworkspacesilent, 3
bind = SUPER CTRL, code:13, movetoworkspacesilent, 4
bind = SUPER CTRL, code:14, movetoworkspacesilent, 5
bind = SUPER CTRL, code:15, movetoworkspacesilent, 6
bind = SUPER CTRL, code:16, movetoworkspacesilent, 7
bind = SUPER CTRL, code:17, movetoworkspacesilent, 8
bind = SUPER CTRL, code:18, movetoworkspacesilent, 9
bind = SUPER CTRL, code:19, movetoworkspacesilent, 10
bind = SUPER CTRL, bracketleft, movetoworkspacesilent, -1 # brackets [ or ]
bind = SUPER CTRL, bracketright, movetoworkspacesilent, +1


bindm = SUPER SHIFT, mouse:272, movewindow
bindm = SUPER SHIFT, mouse:273, resizewindow
