[FileDialog]
history=file:///home/pedro0210/Documents, file:///home/pedro0210/Documents/Installs, file:///home/pedro0210/Documents/Installs/KDE-Story-Blue-Dark-Plasma, file:///home/pedro0210/Videos, file:///home/pedro0210/Downloads, file:///home/pedro0210/Videos/wallpaper_src
lastVisited=file:///home/pedro0210/Videos/wallpaper_src
qtVersion=5.15.17
shortcuts=file:, file:///home/pedro0210
sidebarWidth=121
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xec\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
