$background = rgb({{background | strip}})
$foreground = rgb({{foreground | strip}})
$color0 = rgb({{color5 | strip}})
$color1 = rgb({{color6 | strip}})
$color2 = rgb({{color3 | strip}})
$color3 = rgb({{color5 | strip}})
$color4 = rgb({{color9 | strip}})
