[main_window]
height = 421
width = 406

padding = 10
spacing = 0

text_color = "{{foreground}}"

font = "Pixel Code"

location = "Center"

border.color = "#ff0000"
border.radius = 0
border.width = 0

border.top_left_radius = 10
border.bottom_left_radius = 10
border.top_right_radius = 10
border.bottom_right_radius = 10



gradient_angle = 160
background_colors = ["{{color5}}", "{{color4}}"]
background_image = "~/Dotfiles/quickshell/images/base-border.png"



[inputbar]
line_height = 1
width = 350

[entry]
height = 25
width = 350


text_color = "{{foreground}}"
focus_text_color = "{{color3}}"
