backend = "fastresize"
color_space = "lch"
palette = "dark"

[templates]
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/colors.rasi'

rofi_config.template = 'wallust-config.rasi'
rofi_config.target = '~/.config/rofi/themes/wallust.rasi'

hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/wallust.conf'

wezterm.template = 'colors-wezterm.toml'
wezterm.target = '~/.config/wezterm/colors/wallust.toml'

quickshell.template = 'config.qml'
quickshell.target = '~/.config/quickshell/Config.qml'

wl-kbptr.template = 'wl-kbptr-config'
wl-kbptr.target = '~/.config/wl-kbptr/config'

neopywal.template = 'colors_neopywal.vim'
neopywal.target = '~/.cache/wal/colors-wal.vim'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/themes/kitty-colors.conf'
