
$HyprDir = $HOME/.config/hypr

source= $HyprDir/general_settings/user_settings.conf
source= $HyprDir/workspace/workspace_movement.conf
source= $HyprDir/workspace/special_work_spaces.conf
source= $HyprDir/hardware/monitors.conf
source = $HyprDir/general_settings/window_rules.conf
source = $HyprDir/general_settings/startup_apps.conf
source = $HyprDir/general_settings/shortcuts.conf
source = $HyprDir/env.conf

env = bitdepth,10


