
# FOr intialize rofi

bind = SUPER, V, exec, cliphist list | rofi -dmenu -config ~/.config/rofi/config-clipboard.rasi | cliphist decode | wl-copy

bind = SUPER, SPACE, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window -show-icons

# For yazi

bind = SUPER, y, exec, wezterm start yazi

# For Zoom

bind = SUPER, z, exec, pypr zoom

# For ss
bind = SUPER SHIFT, S, exec, hyprshot -m window -m region --clipboard-only --silent

bind = SUPER, Return, exec, wezterm

# initializing it wl-kbptr
bind = SUPER, SUPER_L, exec, pkill wl-kbptr || wl-kbptr -c $HOME/.config/wl-kbptr/config

# for clicks

# Left button
bind= SUPER,a,exec,wlrctl pointer click left
# Middle button
bind= SUPER,s,exec,wlrctl pointer click middle
# Right button
bind= SUPER,d,exec,wlrctl pointer click right

bind = SUPER SHIFT, Return, exec, pypr toggle term

# for wlogut
bind = SUPER SHIFT, p, exec, kill wlogout | wlogout layer-shell -b 2 -T 100 -B 100 &
