-- Sourcing colors generated by wallust
require("wallust")

hl.config({

	dwindle = {
		preserve_split = true,
		-- window size for special workspaces
		special_scale_factor = 0.95,
	},

	general = {
		-- idunno, newest update don't add this 2, soo yeah
		-- sensitivity=1.00
		-- apply_sens_to_raw=1
		gaps_in = 4,
		gaps_out = 5,
		border_size = 2,
		resize_on_border = true,
		col = {

			active_border = {
				colors = {
					Color0,
					Color1,
					Color0,
					Color1,
					Color0,
				},
				angle = 90,
			},
			inactive_border = Background,
		},

		layout = "dwindle",
	},

	decoration = {

		dim_inactive = true,
		dim_strength = 0.1,
		dim_special = 0.0,

		blur = {
			enabled = true,
			size = 5,
			passes = 2,
			ignore_opacity = true,
			new_optimizations = true,
			special = true,
		},
	},

	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "grp:alt_shift_toggle",
		kb_rules = "",
		repeat_rate = 50,
		repeat_delay = 300,
		numlock_by_default = true,
		left_handed = false,
		follow_mouse = true,
		float_switch_override_focus = false,
	},

	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		mouse_move_enables_dpms = true,

		enable_swallow = true,
		focus_on_activate = false,
		--disable_autoreload = true
	},

	binds = {
		workspace_back_and_forth = true,
		allow_workspace_cycles = true,
		pass_mouse_when_bound = false,
	},

	-- Could help when scaling and not pixelating
	xwayland = {
		force_zero_scaling = true,
	},
})

hl.curve("linear", { type = "bezier", points = { { 0.0, 0.0 }, { 1.0, 1.0 } } })
hl.curve("win", { type = "bezier", points = { { 0.03, 0.9 }, { 0.0, 1.0 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.7, 0.6 }, { 0.1, 0.1 } } })
hl.curve("bounce", { type = "bezier", points = { { 1.1, 1.6 }, { 0.1, 0.85 } } })

hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, bezier = "win", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, bezier = "win", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5, bezier = "win", style = "slide" })
hl.animation({ leaf = "border", enabled = true, speed = 1, bezier = "linear" })
hl.animation({
	leaf = "borderangle",
	enabled = true,
	speed = 100,
	angle = 180,
	bezier = "linear",
	style = "loop",
})
hl.animation({ leaf = "fade", enabled = true, speed = 5, bezier = "overshot" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "win" })
hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "bounce", style = "popin" })

--animations {
--  enabled = yes
--
--  bezier = linear, 0.0, 0.0, 1.0, 1.0
--  bezier = win, 0.03, 0.9, 0, 1
--  bezier = overshot, 0.7, 0.6, 0.1, 1.1
--  bezier = bounce, 1.1, 1.6, 0.1, 0.85
--
--  animation = windowsIn, 1, 5, win, slide
--  animation = windowsOut, 1, 5, win, slide
--  animation = windowsMove, 1, 5, win, slide
--  animation = border, 1, 10, linear
--  animation = borderangle, 1, 180, linear, loop #used by borders and rotating colors
--  animation = fade, 1, 5, overshot
--  animation = workspaces, 1, 5, win
--  animation = windows, 1, 5, bounce, popin
--}
