foreground                      #F6F6F4
background                      #1F1E1D

selection_foreground            #F6F6F4
selection_background            #D59B98

cursor            #D59B98

color0  #464544
color1  #50508C
color2  #B4403B
color3  #6F6E69
color4  #C99260
color5  #A998BA
color6  #E6E6E1
color7  #EAEAE8
color8  #A4A4A2
color9  #50508C
color10 #B4403B
color11 #6F6E69
color12 #C99260
color13 #A998BA
color14 #E6E6E1
color15 #EAEAE8


