$ASSETS = $HOME/.config/hypr/assets

plugin:imgborders {
    enabled = true
    image = $ASSETS/base-border.png
    sizes = 1,2,3,4 # left, right, top, bottom
    insets = 1,2,3,4 # left, right, top, bottom
    scale = 1.2
    smooth = true
    blur = false
}
