# For wallpaper
exec-once = awww-daemon --format xrgb

# For clipboard
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

# For th one and only Miku cursor
exec-once = hyprctl setcursor ffxi-chocobo-cursor 24

exec-once = hyprctl plugin load /nix/store/0khrpgz0avzsk90cclxwpbhhfqswzf5h-hyrpland-plugins/lib/libimgborders.so


# BUG: for some reason hyprctl returns unknown values on the version -j

# Pyprland
exec-once = pypr &
# Quickshell
exec-once = quickshell &

# home-assistant
exec-once = ~/Documents/Shell-Scripts/home-assistant/startup_strip.sh

# Workspaces with shorcuts

# for some reason the system that tracks where to place windows it's messed up cause of hyprland changes
# check messages just in case:

exec-once = [workspace special:spotify silent] spotify

exec-once = [workspace special:wiremix silent] kitty wiremix
exec-once = [workspace special:btop silent] kitty btop
exec-once = [workspace special:openrgb silent] openrgb

# for fast firefox opening (takes a while without an y reason)
exec-once = [workspace special:cached silent] firefox

