
[colors]
# The default text color
foreground = "#BEBFCD"
# The default background color
background = "#17151E"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#676792"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#17151E"
# Specifies the border color of the cursor when the cursor style is set to Block,
# of the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#676792"

# the foreground color of selected text
selection_fg = "#BEBFCD"
# the background color of selected text
selection_bg = "#676792"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = "#676792"

# The color of the split lines between panes
split = "#676792"

ansi = ["#3F3C46", "#11103D", "#111058", "#030275", "#0000A1", "#2A2867", "#444870", "#999BAF"]
brights = ["#6B6C7A", "#11103D", "#111058", "#030275", "#0000A1", "#2A2867", "#444870", "#999BAF"]

