
[colors]
# The default text color
foreground = "#F6F6F4"
# The default background color
background = "#1F1E1D"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#D59B98"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#1F1E1D"
# Specifies the border color of the cursor when the cursor style is set to Block,
# of the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#D59B98"

# the foreground color of selected text
selection_fg = "#F6F6F4"
# the background color of selected text
selection_bg = "#D59B98"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = "#D59B98"

# The color of the split lines between panes
split = "#D59B98"

ansi = ["#464544", "#50508C", "#B4403B", "#6F6E69", "#C99260", "#A998BA", "#E6E6E1", "#EAEAE8"]
brights = ["#A4A4A2", "#50508C", "#B4403B", "#6F6E69", "#C99260", "#A998BA", "#E6E6E1", "#EAEAE8"]

