
[colors]
# The default text color
foreground = "#FAF9F6"
# The default background color
background = "#151213"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#E0847E"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#151213"
# Specifies the border color of the cursor when the cursor style is set to Block,
# of the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#E0847E"

# the foreground color of selected text
selection_fg = "#FAF9F6"
# the background color of selected text
selection_bg = "#E0847E"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = "#E0847E"

# The color of the split lines between panes
split = "#E0847E"

ansi = ["#3C3A3B", "#664717", "#C70E06", "#8E6779", "#AC8E69", "#B5B2E3", "#F0EEE6", "#EFEEEA"]
brights = ["#A7A7A4", "#664717", "#C70E06", "#8E6779", "#AC8E69", "#B5B2E3", "#F0EEE6", "#EFEEEA"]

